In [1]:
import torch
import numpy as np
from utils.dataset import SimpleIterDataset
import os
import onnxruntime as ort

In [2]:
def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

In [3]:
def create_ort_inputs(inputs, input_names):
    return {name: to_numpy(inputs[index]) for (index, name) in enumerate(input_names)}

In [4]:
def run_ort_inference(onnx_path, inputs, input_names):
    ort_session = ort.InferenceSession(onnx_path)
    runSessionParams = ort.RunOptions()
    runSessionParams.log_severity_level = 2
    ort_out = ort_session.run(None, create_ort_inputs(inputs, input_names), run_options = runSessionParams)
    return ort_out

In [5]:
def run_pt_inference(model, inputs):
    return model(*inputs)

In [6]:
def export_onnx(model, inputs, dynamic_axes, input_names, output_names, onnx_path, opset_version = 15):
    torch.onnx.export(model, inputs, onnx_path, input_names=input_names, output_names=output_names, dynamic_axes=dynamic_axes, opset_version=opset_version)
    model_output = run_pt_inference(model, inputs)
    ort_output = run_ort_inference(onnx_path, inputs, input_names)
    print ("Model output - \n{}".format(model_output))
    print ("ORT output - \n{}".format(ort_output))

In [7]:
def create_model_inputs(model_type, num_jets = 4, num_particles_per_jet = 1, device = 'cpu', expectedIntDtype = 'int32'):
    def get_feature_dimension(feature_name, model_types_dims_mapper, default_dims_mapper, model_type):
        dimensions = None
        if feature_name in default_dims_mapper.keys():
            dimensions = default_dims_mapper[feature_name]
        else:
            dimensions = model_types_dims_mapper[model_type][feature_name]
        return dimensions
    
    model_type_dims_mapper = {'ak8_points_pf_sv_full': {'pf_features': 25, 'sv_features': 11}, 'ak8_points_pf_sv_mass_decorr': {'pf_features': 20, 'sv_features': 11}, 'ak4_points_pf_sv_CHS_eta4p7': {'pf_features': 20, 'sv_features': 11}, 'ak8_points_pf_sv_mass_regression': {'pf_features': 25, 'sv_features': 11}}
    default_dims_mapper = {'pf_points': 2, 'pf_mask': 1, 'sv_points': 2, 'sv_mask': 1}
    input_names = ['pf_points', 'pf_features', 'pf_mask', 'sv_points', 'sv_features', 'sv_mask']
    input_names += ['batch_shapes_{}'.format(item) for item in input_names]
    
    inputs = list()
    for input_name in input_names:
        if 'batch_shapes_' not in input_name:
            dimensions = get_feature_dimension(input_name, model_type_dims_mapper, default_dims_mapper, model_type)    
            inputs.append(torch.rand((num_jets * num_particles_per_jet * dimensions, ), dtype = torch.float).to(device))
        else:
            dimensions = get_feature_dimension(input_name.replace('batch_shapes_', ''), model_type_dims_mapper, default_dims_mapper, model_type)    
            datatype = torch.int32 if expectedIntDtype == 'int32' else torch.int64
            inputs.append(torch.tensor([[dimensions, num_particles_per_jet] for _ in range(num_jets)], dtype = datatype).to(device))
    return tuple(inputs), input_names

In [8]:
def get_model(model_type, device = 'cpu'):
    data_config_name = 'data/AK4/{}.yaml'.format(model_type)
    if model_type != 'ak4_points_pf_sv_CHS_eta4p7':
        data_config_name = 'data/{}.yaml'.format(model_type)
    import networks.particle_net_ak4_pf_sv as network_module1
    import networks.particle_net_pf_sv as network_module2
    import networks.particle_net_pf_sv_mass_regression as network_module3
    
    model_state_dict = data_config_name.replace('.yaml','.pt')
    jit_model_save = data_config_name.replace('.yaml','_ragged_gpu_jit.pt')
    onnx_model = data_config_name.replace('.yaml','.onnx')
    
    data_config = SimpleIterDataset([], data_config_name, for_training=False).config
    model, model_info = None, None
    
    network_module = None
    if model_type == 'ak8_points_pf_sv_full':
        network_module = network_module2
    elif model_type == 'ak8_points_pf_sv_mass_decorr':
        network_module = network_module2
    elif model_type == 'ak4_points_pf_sv_CHS_eta4p7':
        network_module = network_module1
    else:
        network_module = network_module3
    
    model, model_info = network_module.get_model(data_config, for_inference=True)
    model = torch.jit.script(model)
    model.load_state_dict(torch.load(model_state_dict, map_location=torch.device(device)))
    model.eval()
    
    return model, model_info

In [9]:
def export_multiple_models(model_types):
    models = list() 
    for model_type in model_types:
        print ("Export model type - {}".format(model_type)) 
        model, model_info = get_model(model_type)
        model_inputs, input_names = create_model_inputs(model_type, num_jets = 9, num_particles_per_jet = 3)
        onnx_path = "exported_models/{}.onnx".format(model_type)
        export_onnx(model, model_inputs, model_info['dynamic_axes'], input_names, model_info['output_names'], onnx_path)
        models.append(model)
    return models

In [10]:
def test_exported_models(models, model_types, configs = [{'num_jets': 1, 'num_particles_per_jet': 13}, {'num_jets': 1, 'num_particles_per_jet': 1}, {'num_jets': 17, 'num_particles_per_jet': 3}, {'num_jets': 16, 'num_particles_per_jet': 20}]):
    for index, model_type in enumerate(model_types):
        model = models[index]
        onnx_path = "exported_models/{}.onnx".format(model_type)
        print ("Model Type - {}\n".format(model_type))
        print ("------------")
        for config in configs:
            print ("Config - Num Jets = {} | Num particles per jet = {}".format(config['num_jets'], config['num_particles_per_jet']))
            test_model_inputs, test_model_input_names = create_model_inputs(model_type, **config)
            print ("PT inference - \n{}\n".format(run_pt_inference(model, test_model_inputs)))
            print ("ORT inference - \n{}\n".format(run_ort_inference(onnx_path, test_model_inputs, test_model_input_names)))

In [11]:
#Test PT model
model_type = 'ak8_points_pf_sv_full'
model_inputs, names = create_model_inputs(model_type)
run_pt_inference(get_model(model_type)[0], model_inputs)

tensor([[9.9208e-01, 3.5801e-04, 3.2226e-05, 3.0899e-08, 6.3638e-09, 5.5457e-08,
         1.8243e-03, 2.8271e-04, 8.1947e-08, 8.5341e-04, 2.2260e-05, 1.2879e-07,
         1.9996e-03, 4.3198e-05, 3.3491e-04, 2.1666e-03, 2.6601e-06, 5.5280e-07,
         9.8616e-11, 1.6854e-16],
        [9.3783e-01, 1.1451e-05, 7.2551e-03, 3.9257e-07, 1.9478e-09, 3.3066e-05,
         3.4399e-03, 1.1821e-02, 5.8585e-08, 3.0253e-04, 6.0421e-07, 2.2767e-10,
         5.8198e-03, 3.2639e-04, 1.9109e-02, 1.4045e-02, 1.6632e-06, 1.3285e-06,
         1.4630e-11, 9.1555e-20],
        [8.2083e-02, 6.2414e-02, 2.5899e-04, 4.4329e-05, 1.5275e-06, 6.1414e-11,
         9.9265e-02, 8.7922e-09, 1.3300e-10, 1.7062e-04, 7.7889e-06, 2.1681e-10,
         6.7002e-01, 2.4259e-03, 7.6922e-02, 6.2129e-03, 1.1962e-05, 1.6366e-04,
         3.8962e-11, 3.1072e-21],
        [1.0079e-03, 7.3534e-08, 8.7776e-10, 8.6493e-13, 4.6508e-23, 2.2074e-14,
         1.4188e-05, 3.2068e-07, 1.3446e-10, 1.0645e-05, 4.1524e-08, 6.4263e-10,
       

In [12]:
model_types = ['ak8_points_pf_sv_full', 'ak4_points_pf_sv_CHS_eta4p7', 'ak8_points_pf_sv_mass_decorr', 'ak8_points_pf_sv_mass_regression']
models = export_multiple_models(model_types)

Export model type - ak8_points_pf_sv_full


/Users/nirmalthomas/Library/Python/3.8/lib/python/site-packages/torch/onnx/symbolic_helper.py:719: UserWarning: allowzero=0 by default. In order to honor zero value in shape use allowzero=1
  warnings.warn("allowzero=0 by default. In order to honor zero value in shape use allowzero=1")
2022-08-02 20:45:47.110028 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:45:47.126260 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:47.126274 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:47.126281 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not u

Model output - 
tensor([[8.5396e-01, 4.4762e-04, 8.4531e-06, 1.0558e-08, 2.5307e-07, 1.2812e-05,
         3.7738e-02, 3.8432e-05, 3.4099e-10, 2.4257e-02, 3.9522e-05, 1.0037e-08,
         4.5330e-02, 3.0871e-05, 1.6279e-02, 2.1849e-02, 3.9206e-06, 4.4708e-06,
         1.1786e-12, 2.3452e-24],
        [4.4913e-01, 6.6978e-03, 1.9181e-03, 1.8567e-04, 3.5931e-06, 3.6394e-02,
         1.7986e-01, 1.9027e-02, 1.9602e-05, 1.5800e-02, 3.2526e-03, 1.7824e-05,
         3.2105e-02, 2.8845e-03, 2.4913e-01, 3.5242e-03, 1.9961e-05, 2.1311e-05,
         5.3273e-09, 1.0053e-13],
        [2.6818e-01, 4.3709e-02, 2.2713e-05, 2.1409e-06, 2.2403e-08, 5.3475e-05,
         9.7054e-02, 1.3653e-09, 2.5183e-10, 1.4863e-03, 4.6540e-10, 7.2098e-10,
         3.7138e-01, 3.1737e-08, 1.8377e-01, 3.4347e-02, 4.7519e-11, 1.0308e-06,
         5.2877e-19, 9.9712e-26],
        [6.1704e-02, 2.3860e-02, 1.6936e-03, 6.4505e-04, 1.7379e-03, 3.6792e-02,
         8.0800e-01, 2.2512e-06, 4.8250e-07, 6.6018e-03, 1.6681e-06, 2.6

2022-08-02 20:45:49.794140 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:45:49.810991 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:49.811007 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:49.811013 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:49.811019 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:49.811024 [W:onnxruntime:, gr

Model output - 
tensor([[5.4242e-02, 2.6094e-01, 2.9431e-02, 4.4001e-02, 5.4686e-03, 2.0992e-01,
         3.9599e-01, 1.3027e-07],
        [6.9841e-03, 9.9152e-01, 9.7432e-05, 4.5907e-04, 2.7181e-07, 5.5412e-05,
         8.8537e-04, 1.7270e-24],
        [2.4976e-01, 2.0081e-01, 8.0664e-02, 4.0738e-02, 1.0853e-02, 1.8866e-01,
         2.2752e-01, 9.9937e-04],
        [1.3596e-01, 2.6010e-01, 4.9985e-02, 3.4294e-02, 2.9337e-03, 1.4221e-01,
         3.7452e-01, 3.5834e-09],
        [1.4825e-01, 1.0894e-01, 6.8103e-02, 3.5396e-02, 2.1058e-02, 3.0745e-01,
         3.1080e-01, 1.0780e-06],
        [1.5781e-02, 1.3842e-02, 1.3438e-03, 3.9645e-04, 2.0902e-04, 4.5438e-03,
         9.4266e-03, 9.5446e-01],
        [1.4623e-01, 1.3251e-01, 7.6268e-02, 4.2561e-02, 1.2807e-02, 3.1218e-01,
         2.7514e-01, 2.2928e-03],
        [1.6859e-02, 9.8043e-01, 1.7296e-04, 8.8402e-04, 4.6677e-07, 1.8399e-04,
         1.4732e-03, 4.4199e-16],
        [2.2279e-02, 8.3414e-01, 4.4059e-03, 1.2906e-02, 3.8915e

2022-08-02 20:45:52.916652 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:45:52.933079 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:52.933095 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:52.933102 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:52.933107 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:52.933113 [W:onnxruntime:, gr

Model output - 
tensor([[5.6486e-11, 9.3758e-11, 6.4973e-23, 1.0000e+00, 5.2284e-09, 2.5922e-11,
         9.1718e-15, 7.7543e-23],
        [3.8448e-13, 7.6233e-13, 8.8697e-31, 1.0000e+00, 9.2576e-17, 1.1266e-15,
         1.0470e-26, 9.5221e-33],
        [2.3470e-18, 1.4142e-13, 9.6375e-29, 1.0000e+00, 2.5258e-11, 3.1396e-13,
         1.8645e-22, 4.8984e-33],
        [3.1916e-11, 1.6189e-12, 7.6795e-24, 1.0000e+00, 4.3841e-08, 2.1851e-07,
         2.6073e-13, 1.6856e-21],
        [1.0719e-09, 1.8077e-08, 7.0191e-18, 1.0000e+00, 2.8324e-10, 3.2965e-09,
         6.9987e-17, 5.3844e-20],
        [1.9157e-07, 8.0636e-10, 3.5047e-28, 1.0000e+00, 8.5574e-14, 2.0138e-11,
         6.3960e-24, 6.7067e-34],
        [8.3911e-18, 1.6846e-15, 1.3890e-30, 1.0000e+00, 4.3371e-10, 1.3231e-10,
         3.7104e-17, 1.8748e-33],
        [1.1365e-15, 3.2694e-15, 4.0158e-33, 1.0000e+00, 1.0929e-22, 1.7499e-12,
         1.0446e-35, 0.0000e+00],
        [3.6350e-14, 4.8367e-09, 1.3602e-16, 1.0000e+00, 5.7239e

2022-08-02 20:45:56.015402 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:45:56.032490 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:56.032508 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:56.032514 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:56.032520 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:56.032526 [W:onnxruntime:, gr

In [13]:
test_exported_models(models, model_types)

Model Type - ak8_points_pf_sv_full

------------
Config - Num Jets = 1 | Num particles per jet = 13
PT inference - 
tensor([[6.2762e-01, 2.4294e-01, 1.1028e-03, 1.6587e-03, 4.7235e-05, 9.3204e-03,
         3.8988e-02, 7.7117e-03, 6.3684e-04, 6.0335e-04, 3.6322e-04, 9.9051e-05,
         5.5330e-03, 2.5246e-03, 5.5951e-02, 4.4491e-03, 4.2780e-04, 2.1616e-05,
         1.2838e-06, 1.5825e-06]], grad_fn=<SoftmaxBackward0>)



2022-08-02 20:45:57.121262 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:45:57.138301 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:57.138318 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:57.138325 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:57.138330 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:57.138336 [W:onnxruntime:, gr

ORT inference - 
[array([[6.2761647e-01, 2.4294288e-01, 1.1028134e-03, 1.6586527e-03,
        4.7234760e-05, 9.3203709e-03, 3.8987659e-02, 7.7116643e-03,
        6.3683791e-04, 6.0335035e-04, 3.6321278e-04, 9.9050092e-05,
        5.5329991e-03, 2.5246202e-03, 5.5950753e-02, 4.4491175e-03,
        4.2779706e-04, 2.1615504e-05, 1.2838378e-06, 1.5825246e-06]],
      dtype=float32)]

Config - Num Jets = 1 | Num particles per jet = 1
PT inference - 
tensor([[1.3277e-01, 1.0517e-03, 3.0120e-01, 4.9446e-01, 7.5892e-04, 6.1658e-02,
         6.5323e-03, 1.3072e-03, 5.3140e-05, 9.3049e-06, 9.7914e-06, 1.0962e-04,
         7.9100e-05, 2.6963e-06, 1.7280e-06, 7.5194e-07, 1.8486e-10, 7.0569e-07,
         1.1496e-09, 5.1858e-10]], grad_fn=<SoftmaxBackward0>)



2022-08-02 20:45:58.160480 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:45:58.177057 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:58.177072 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:58.177079 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:58.177084 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:58.177090 [W:onnxruntime:, gr

ORT inference - 
[array([[1.3277404e-01, 1.0516784e-03, 3.0119511e-01, 4.9445587e-01,
        7.5891789e-04, 6.1658066e-02, 6.5323035e-03, 1.3072097e-03,
        5.3139822e-05, 9.3048784e-06, 9.7914253e-06, 1.0962389e-04,
        7.9099460e-05, 2.6962805e-06, 1.7280139e-06, 7.5193657e-07,
        1.8485159e-10, 7.0568279e-07, 1.1496062e-09, 5.1857746e-10]],
      dtype=float32)]

Config - Num Jets = 17 | Num particles per jet = 3
PT inference - 
tensor([[4.3435e-02, 5.3486e-06, 7.9319e-11, 8.7408e-15, 3.1958e-24, 7.1643e-16,
         1.9543e-04, 5.0750e-09, 6.2599e-13, 1.1873e-04, 1.4750e-09, 3.3469e-11,
         1.1898e-01, 1.2434e-06, 8.3693e-01, 3.3111e-04, 1.4773e-12, 3.5463e-11,
         5.9173e-24, 6.0376e-39],
        [2.0903e-01, 2.3691e-03, 6.3707e-04, 2.2469e-05, 5.3293e-06, 3.9132e-06,
         6.6491e-03, 7.2745e-02, 3.1417e-05, 2.9404e-01, 2.6805e-02, 2.8694e-04,
         1.8908e-01, 9.8338e-03, 1.7593e-01, 1.2318e-02, 5.1630e-05, 1.6202e-04,
         2.4158e-08, 3.1505e-2

2022-08-02 20:45:59.530898 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:45:59.547356 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:59.547371 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:59.547378 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:59.547384 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:45:59.547390 [W:onnxruntime:, gr

ORT inference - 
[array([[4.34351973e-02, 5.34859146e-06, 7.93187946e-11, 8.74087264e-15,
        3.19578676e-24, 7.16436137e-16, 1.95434230e-04, 5.07502307e-09,
        6.25987543e-13, 1.18731456e-04, 1.47501567e-09, 3.34694286e-11,
        1.18981741e-01, 1.24343126e-06, 8.36931169e-01, 3.31106596e-04,
        1.47732781e-12, 3.54630700e-11, 5.91725472e-24, 0.00000000e+00],
       [2.09033176e-01, 2.36913818e-03, 6.37070101e-04, 2.24690193e-05,
        5.32920558e-06, 3.91309641e-06, 6.64906437e-03, 7.27451965e-02,
        3.14170029e-05, 2.94038951e-01, 2.68048681e-02, 2.86940864e-04,
        1.89079478e-01, 9.83375870e-03, 1.75927579e-01, 1.23179769e-02,
        5.16296532e-05, 1.62019656e-04, 2.41580356e-08, 3.15045824e-20],
       [9.99726355e-01, 7.10146537e-08, 1.75298268e-07, 7.71706592e-13,
        1.10768916e-09, 1.53943347e-06, 8.52107187e-05, 9.86851010e-05,
        3.29347172e-13, 4.18324708e-09, 3.90991059e-12, 4.14300358e-17,
        6.00252577e-07, 1.03072426e-10, 1.68

2022-08-02 20:46:02.391086 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:46:02.408426 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:02.408443 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:02.408450 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:02.408456 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:02.408462 [W:onnxruntime:, gr

ORT inference - 
[array([[7.31520474e-01, 1.29161760e-01, 9.80579644e-04, 2.24150921e-04,
        3.00055490e-06, 1.06771793e-02, 4.83846478e-02, 4.36986005e-03,
        1.84348115e-04, 5.69412112e-03, 1.20219171e-04, 4.30304062e-05,
        2.50297338e-02, 4.59063449e-04, 2.28933785e-02, 2.02236865e-02,
        1.08660097e-05, 1.98578273e-05, 2.19362550e-09, 1.46821270e-12],
       [5.34620166e-01, 9.51849949e-03, 1.99700353e-05, 3.12613224e-07,
        3.18255838e-11, 8.63858531e-07, 2.99641564e-02, 5.63829199e-05,
        5.93867924e-07, 4.39390428e-02, 4.63472452e-06, 5.22279652e-06,
        2.10265413e-01, 2.72004618e-05, 6.47196174e-02, 1.06857665e-01,
        2.35023609e-08, 2.80303254e-07, 2.23543260e-15, 3.64588437e-19],
       [7.30326712e-01, 5.89713715e-02, 2.46378186e-05, 1.77973675e-06,
        1.83558555e-08, 1.23958989e-06, 1.35434857e-02, 1.19128723e-04,
        1.96087581e-06, 8.11805762e-03, 3.34760148e-06, 4.31693297e-06,
        4.29565981e-02, 3.33144999e-05, 1.11

2022-08-02 20:46:03.447683 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:46:03.464424 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:03.464441 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:03.464448 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:03.464454 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:03.464459 [W:onnxruntime:, gr

ORT inference - 
[array([[1.2927015e-01, 7.5863910e-01, 1.6292347e-02, 6.0022663e-02,
        6.4996147e-04, 2.5454121e-02, 9.6716145e-03, 1.4286579e-16]],
      dtype=float32)]

Config - Num Jets = 1 | Num particles per jet = 1
PT inference - 
tensor([[1.2231e-03, 4.4089e-05, 1.1783e-04, 2.6246e-05, 1.3172e-06, 2.5347e-04,
         1.4620e-03, 9.9687e-01]], grad_fn=<SoftmaxBackward0>)



2022-08-02 20:46:04.316264 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:46:04.332902 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:04.332921 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:04.332928 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:04.332934 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:04.332940 [W:onnxruntime:, gr

ORT inference - 
[array([[1.22310105e-03, 4.40884687e-05, 1.17832125e-04, 2.62462581e-05,
        1.31722288e-06, 2.53469276e-04, 1.46203954e-03, 9.96871889e-01]],
      dtype=float32)]

Config - Num Jets = 17 | Num particles per jet = 3
PT inference - 
tensor([[1.5494e-01, 3.7168e-01, 6.3700e-02, 6.6734e-02, 3.1501e-03, 1.0871e-01,
         2.3108e-01, 1.4832e-07],
        [1.7571e-01, 4.6644e-01, 6.5660e-02, 8.7870e-02, 6.5705e-03, 8.3156e-02,
         1.1459e-01, 1.6059e-10],
        [4.3824e-01, 2.6132e-01, 6.7806e-02, 5.7727e-02, 5.3703e-03, 5.3380e-02,
         9.1372e-02, 2.4786e-02],
        [2.9600e-01, 1.6471e-01, 1.0994e-01, 5.6891e-02, 1.4082e-02, 1.5389e-01,
         2.0441e-01, 7.7641e-05],
        [1.5090e-01, 3.5879e-01, 6.1904e-02, 6.0500e-02, 3.9609e-03, 1.3265e-01,
         2.3129e-01, 1.3973e-07],
        [2.3033e-01, 1.0601e-01, 8.6621e-02, 3.6492e-02, 1.6555e-02, 1.8466e-01,
         1.5820e-01, 1.8113e-01],
        [1.5740e-02, 9.8212e-01, 1.7611e-04, 5.3416e-04,

2022-08-02 20:46:05.043336 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:05.043377 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:05.043392 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:05.043399 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:05.043405 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '172'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:05.043410 [W:onnxruntime:, graph.cc:3559 CleanUn

ORT inference - 
[array([[1.54943392e-01, 3.71676564e-01, 6.36999235e-02, 6.67342767e-02,
        3.15014785e-03, 1.08713984e-01, 2.31081545e-01, 1.48316914e-07],
       [1.75710276e-01, 4.66440916e-01, 6.56605065e-02, 8.78701508e-02,
        6.57054456e-03, 8.31564069e-02, 1.14591219e-01, 1.60592983e-10],
       [4.38236207e-01, 2.61322439e-01, 6.78055212e-02, 5.77274673e-02,
        5.37026022e-03, 5.33797443e-02, 9.13719237e-02, 2.47863922e-02],
       [2.96004772e-01, 1.64707229e-01, 1.09940052e-01, 5.68911806e-02,
        1.40823778e-02, 1.53885588e-01, 2.04411134e-01, 7.76417146e-05],
       [1.50902122e-01, 3.58789951e-01, 6.19043559e-02, 6.04996271e-02,
        3.96094238e-03, 1.32654548e-01, 2.31288359e-01, 1.39724719e-07],
       [2.30335429e-01, 1.06005803e-01, 8.66212994e-02, 3.64916176e-02,
        1.65550578e-02, 1.84664309e-01, 1.58202022e-01, 1.81124508e-01],
       [1.57402623e-02, 9.82116640e-01, 1.76105372e-04, 5.34161809e-04,
        8.45100601e-07, 1.94120381e-04, 

2022-08-02 20:46:06.566508 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:46:06.584138 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:06.584155 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:06.584162 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:06.584168 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:06.584174 [W:onnxruntime:, gr

ORT inference - 
[array([[2.08020180e-01, 5.93627453e-01, 3.14560235e-02, 4.56108488e-02,
        2.23913975e-03, 1.09060913e-01, 9.98533331e-03, 1.30795778e-15],
       [1.98212057e-01, 7.22816527e-01, 1.48468865e-02, 4.73305322e-02,
        4.77150083e-04, 1.57944802e-02, 5.22352639e-04, 1.64424352e-15],
       [1.90293238e-01, 6.48909748e-01, 2.60650869e-02, 4.46864367e-02,
        1.55862840e-03, 6.91305846e-02, 1.93563271e-02, 1.76619459e-16],
       [3.41180205e-01, 4.83369380e-01, 2.96643786e-02, 4.71962430e-02,
        5.37486700e-03, 9.02622789e-02, 2.95256358e-03, 1.03216906e-11],
       [1.94236577e-01, 2.66529411e-01, 5.78312315e-02, 3.60608101e-02,
        8.50217976e-03, 2.25006133e-01, 2.11833641e-01, 1.79817522e-10],
       [1.43209174e-01, 7.89384782e-01, 1.07977316e-02, 2.10612640e-02,
        3.42891755e-04, 2.13297363e-02, 1.38744889e-02, 9.03214731e-20],
       [7.29532614e-02, 8.26078892e-01, 8.82762764e-03, 2.33767834e-02,
        2.49127275e-04, 4.78113033e-02, 

2022-08-02 20:46:07.546677 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:46:07.563864 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:07.563880 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:07.563886 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:07.563893 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:07.563899 [W:onnxruntime:, gr

ORT inference - 
[array([[4.2794906e-07, 8.1471535e-06, 1.0587628e-12, 9.4296676e-01,
        4.7900476e-02, 9.1115842e-03, 1.2632538e-05, 2.4386959e-15]],
      dtype=float32)]

Config - Num Jets = 1 | Num particles per jet = 1
PT inference - 
tensor([[1.5572e-12, 4.3011e-05, 2.5680e-09, 9.9996e-01, 1.1276e-12, 6.4380e-15,
         2.6747e-19, 1.5502e-22]], grad_fn=<SoftmaxBackward0>)



2022-08-02 20:46:08.492374 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:46:08.508653 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:08.508670 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:08.508677 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:08.508683 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:08.508689 [W:onnxruntime:, gr

ORT inference - 
[array([[1.5572317e-12, 4.3012162e-05, 2.5680178e-09, 9.9995697e-01,
        1.1276380e-12, 6.4379133e-15, 2.6746508e-19, 1.5501411e-22]],
      dtype=float32)]

Config - Num Jets = 17 | Num particles per jet = 3
PT inference - 
tensor([[5.7097e-05, 7.3798e-09, 3.5390e-24, 9.9994e-01, 7.3936e-14, 3.1483e-07,
         2.0252e-20, 1.2597e-23],
        [1.8497e-09, 4.1087e-06, 1.7464e-14, 1.0000e+00, 2.9625e-13, 5.7777e-12,
         2.4784e-22, 9.1930e-29],
        [1.1664e-09, 6.4677e-12, 4.4267e-21, 1.0000e+00, 5.9789e-18, 6.9052e-14,
         1.3845e-25, 2.5856e-30],
        [4.4172e-11, 4.8734e-14, 2.9284e-35, 1.0000e+00, 9.4183e-13, 5.6436e-12,
         1.1983e-20, 1.1260e-33],
        [2.0615e-04, 8.4246e-07, 6.9042e-14, 9.9979e-01, 7.7180e-20, 3.5807e-13,
         1.6213e-28, 3.4844e-28],
        [7.5970e-10, 9.1062e-04, 1.3322e-17, 9.9909e-01, 2.3925e-13, 4.7343e-11,
         1.8510e-25, 1.2307e-34],
        [1.7977e-06, 5.5349e-07, 1.3819e-15, 1.0000e+00, 1.0831e

2022-08-02 20:46:09.751312 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:46:09.768476 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:09.768493 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:09.768500 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:09.768507 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:09.768512 [W:onnxruntime:, gr

ORT inference - 
[array([[5.70971133e-05, 7.37978079e-09, 3.53900751e-24, 9.99942541e-01,
        7.39390781e-14, 3.14825598e-07, 2.02525043e-20, 1.25971794e-23],
       [1.84968607e-09, 4.10875782e-06, 1.74640982e-14, 9.99995947e-01,
        2.96256834e-13, 5.77777192e-12, 2.47847222e-22, 9.19365650e-29],
       [1.16640464e-09, 6.46766538e-12, 4.42665826e-21, 1.00000000e+00,
        5.97872002e-18, 6.90496041e-14, 1.38447875e-25, 2.58554384e-30],
       [4.41718398e-11, 4.87341118e-14, 2.92837856e-35, 1.00000000e+00,
        9.41802409e-13, 5.64350086e-12, 1.19824729e-20, 1.12594662e-33],
       [2.06154800e-04, 8.42448060e-07, 6.90430718e-14, 9.99792993e-01,
        7.71780320e-20, 3.58071428e-13, 1.62122941e-28, 3.48430314e-28],
       [7.59704188e-10, 9.10630275e-04, 1.33218323e-17, 9.99089360e-01,
        2.39252330e-13, 4.73432404e-11, 1.85094317e-25, 1.23070918e-34],
       [1.79769097e-06, 5.53492043e-07, 1.38190471e-15, 9.99995470e-01,
        1.08307427e-06, 1.10232929e-06, 

2022-08-02 20:46:11.912256 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:46:11.928952 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:11.928969 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:11.928976 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:11.928981 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:11.928987 [W:onnxruntime:, gr

ORT inference - 
[array([[7.79077289e-11, 2.84833099e-08, 5.37737482e-20, 9.99688745e-01,
        1.66794969e-04, 1.44540900e-04, 4.11438557e-11, 7.56473851e-27],
       [8.59965340e-16, 3.01878992e-13, 9.78426184e-27, 9.99969959e-01,
        2.34450090e-05, 6.57411465e-06, 7.63097878e-14, 2.65274579e-35],
       [8.50650453e-11, 1.85252681e-11, 7.37519598e-20, 9.99612868e-01,
        1.92693449e-04, 1.94434921e-04, 1.55788937e-09, 1.94439365e-21],
       [5.33432543e-09, 2.97996738e-08, 1.76647393e-13, 9.84946609e-01,
        1.49066616e-02, 1.46684819e-04, 4.59765381e-08, 1.53513985e-17],
       [4.17884536e-07, 1.31250900e-07, 2.21559862e-19, 9.92649615e-01,
        1.90751720e-03, 5.44214528e-03, 1.54470058e-07, 2.65324485e-17],
       [1.60022343e-12, 3.84147748e-11, 5.21484540e-19, 9.97503817e-01,
        2.31551845e-03, 1.80660762e-04, 3.26000538e-09, 6.64098325e-23],
       [9.02244608e-08, 2.11682121e-07, 1.79229986e-14, 9.85921919e-01,
        2.64353608e-03, 1.14336982e-02, 

2022-08-02 20:46:13.051873 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:46:13.068819 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:13.068835 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:13.068842 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:13.068849 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:13.068855 [W:onnxruntime:, gr

ORT inference - 
[array([[1.]], dtype=float32)]

Config - Num Jets = 1 | Num particles per jet = 1
PT inference - 
tensor([[1.]], grad_fn=<SoftmaxBackward0>)



2022-08-02 20:46:14.081918 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:46:14.099238 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:14.099255 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:14.099262 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:14.099267 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:14.099273 [W:onnxruntime:, gr

ORT inference - 
[array([[1.]], dtype=float32)]

Config - Num Jets = 17 | Num particles per jet = 3
PT inference - 
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]], grad_fn=<SoftmaxBackward0>)



2022-08-02 20:46:15.345655 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:46:15.361736 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:15.361753 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:15.361760 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:15.361765 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:15.361771 [W:onnxruntime:, gr

ORT inference - 
[array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)]

Config - Num Jets = 16 | Num particles per jet = 20
PT inference - 
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]], grad_fn=<SoftmaxBackward0>)

ORT inference - 
[array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)]



2022-08-02 20:46:17.470309 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_447'
2022-08-02 20:46:17.486889 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '170'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:17.486905 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '169'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:17.486911 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '173'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:17.486917 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '159'. It is not used by any node and should be removed from the model.
2022-08-02 20:46:17.486922 [W:onnxruntime:, gr