In [13]:
import torch
import numpy as np
from utils.dataset import SimpleIterDataset
import os
import onnxruntime as ort
import torch.autograd.profiler as profiler

In [14]:
def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

In [15]:
def create_ort_inputs(inputs, input_names):
    return {name: to_numpy(inputs[index]) for (index, name) in enumerate(input_names)}

In [16]:
def run_ort_inference(onnx_path, inputs, input_names):
    ort_session = ort.InferenceSession(onnx_path)
    runSessionParams = ort.RunOptions()
    runSessionParams.log_severity_level = 2
    ort_out = ort_session.run(None, create_ort_inputs(inputs, input_names), run_options = runSessionParams)
    return ort_out

In [17]:
def run_pt_inference(model, inputs):
    with profiler.profile(with_stack=True, profile_memory=True) as prof:
        output = model(*inputs)
    print(prof.key_averages(group_by_stack_n=5).table(sort_by='self_cpu_time_total', row_limit=5))
    return output

In [18]:
def export_onnx(model, inputs, dynamic_axes, input_names, output_names, onnx_path, opset_version = 15):
    torch.onnx.export(model, inputs, onnx_path, input_names=input_names, output_names=output_names, dynamic_axes=dynamic_axes, opset_version=opset_version)
    model_output = run_pt_inference(model, inputs)
    ort_output = run_ort_inference(onnx_path, inputs, input_names)
    print ("Model output - \n{}".format(model_output))
    print ("ORT output - \n{}".format(ort_output))

In [19]:
def flatten(l):
    result = list()
    for subL in l:
        result.extend(subL)
    return result

In [20]:
def create_model_inputs(model_type, num_jets = 4, num_particles_per_jet = 1, device = 'cpu', expectedIntDtype = 'int32'):
    def get_feature_dimension(feature_name, model_types_dims_mapper, default_dims_mapper, model_type):
        dimensions = None
        if feature_name in default_dims_mapper.keys():
            dimensions = default_dims_mapper[feature_name]
        else:
            dimensions = model_types_dims_mapper[model_type][feature_name]
        return dimensions
    
    model_type_dims_mapper = {'ak8_points_pf_sv_full': {'pf_features': 25, 'sv_features': 11}, 'ak8_points_pf_sv_mass_decorr': {'pf_features': 20, 'sv_features': 11}, 'ak4_points_pf_sv_CHS_eta4p7': {'pf_features': 20, 'sv_features': 11}, 'ak8_points_pf_sv_mass_regression': {'pf_features': 25, 'sv_features': 11}}
    default_dims_mapper = {'pf_points': 2, 'pf_mask': 1, 'sv_points': 2, 'sv_mask': 1}
    input_names = ['pf_points', 'pf_features', 'pf_mask', 'sv_points', 'sv_features', 'sv_mask']
    input_names += ['batch_shapes_{}'.format(item) for item in input_names]
    
    inputs = list()
    for input_name in input_names:
        if 'batch_shapes_' not in input_name:
            dimensions = get_feature_dimension(input_name, model_type_dims_mapper, default_dims_mapper, model_type)    
            inputs.append(torch.rand((num_jets * num_particles_per_jet * dimensions, ), dtype = torch.float).to(device))
        else:
            dimensions = get_feature_dimension(input_name.replace('batch_shapes_', ''), model_type_dims_mapper, default_dims_mapper, model_type)    
            datatype = torch.int32 if expectedIntDtype == 'int32' else torch.int64
            inputs.append(torch.tensor(flatten([[dimensions, num_particles_per_jet] for _ in range(num_jets)]), dtype = datatype).to(device))
    return tuple(inputs), input_names

In [21]:
def get_model(model_type, device = 'cpu'):
    data_config_name = 'data/AK4/{}.yaml'.format(model_type)
    if model_type != 'ak4_points_pf_sv_CHS_eta4p7':
        data_config_name = 'data/{}.yaml'.format(model_type)
    import networks.particle_net_ak4_pf_sv as network_module1
    import networks.particle_net_pf_sv as network_module2
    import networks.particle_net_pf_sv_mass_regression as network_module3
    
    model_state_dict = data_config_name.replace('.yaml','.pt')
    jit_model_save = data_config_name.replace('.yaml','_ragged_gpu_jit.pt')
    onnx_model = data_config_name.replace('.yaml','.onnx')
    
    data_config = SimpleIterDataset([], data_config_name, for_training=False).config
    model, model_info = None, None
    
    network_module = None
    if model_type == 'ak8_points_pf_sv_full':
        network_module = network_module2
    elif model_type == 'ak8_points_pf_sv_mass_decorr':
        network_module = network_module2
    elif model_type == 'ak4_points_pf_sv_CHS_eta4p7':
        network_module = network_module1
    else:
        network_module = network_module3
    
    model, model_info = network_module.get_model(data_config, for_inference=True)
    model = torch.jit.script(model)
    model.load_state_dict(torch.load(model_state_dict, map_location=torch.device(device)))
    model.eval()
    
    return model, model_info

In [22]:
def export_multiple_models(model_types):
    models = list() 
    for model_type in model_types:
        print ("Export model type - {}".format(model_type)) 
        model, model_info = get_model(model_type)
        model_inputs, input_names = create_model_inputs(model_type, num_jets = 9, num_particles_per_jet = 3)
        onnx_path = "exported_models/{}.onnx".format(model_type)
        export_onnx(model, model_inputs, model_info['dynamic_axes'], input_names, model_info['output_names'], onnx_path)
        models.append(model)
    return models

In [23]:
def test_exported_models(models, model_types, configs = [{'num_jets': 1, 'num_particles_per_jet': 13}, {'num_jets': 1, 'num_particles_per_jet': 1}, {'num_jets': 17, 'num_particles_per_jet': 3}, {'num_jets': 16, 'num_particles_per_jet': 20}]):
    for index, model_type in enumerate(model_types):
        model = models[index]
        onnx_path = "exported_models/{}.onnx".format(model_type)
        print ("Model Type - {}\n".format(model_type))
        print ("------------")
        for config in configs:
            print ("Config - Num Jets = {} | Num particles per jet = {}".format(config['num_jets'], config['num_particles_per_jet']))
            test_model_inputs, test_model_input_names = create_model_inputs(model_type, **config)
            print ("PT inference - \n{}\n".format(run_pt_inference(model, test_model_inputs)))
            print ("ORT inference - \n{}\n".format(run_ort_inference(onnx_path, test_model_inputs, test_model_input_names)))

In [24]:
#Test PT model
model_type = 'ak8_points_pf_sv_full'
model_inputs, names = create_model_inputs(model_type)
run_pt_inference(get_model(model_type)[0], model_inputs)

--------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ---------------------------------------------------------------------------  
                            Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg       CPU Mem  Self CPU Mem    # of Calls  Source Location                                                              
--------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ---------------------------------------------------------------------------  
        aten::mkldnn_convolution        41.75%      67.795ms        41.78%      67.844ms       7.538ms      36.09 Mb           0 b             9  ....8/lib/python/site-packages/torch/nn/modules/conv.py(443): _conv_forward  
                                                                                                        

tensor([[2.1865e-02, 6.8637e-07, 6.4621e-09, 7.1645e-13, 3.1260e-20, 1.1702e-16,
         7.4372e-07, 9.4940e-07, 9.3260e-11, 2.7153e-03, 5.4914e-06, 4.3287e-09,
         1.5496e-01, 5.7763e-04, 8.1777e-01, 2.1090e-03, 4.5155e-07, 1.3723e-08,
         3.6713e-15, 1.6167e-25],
        [9.9954e-01, 1.8797e-06, 1.1591e-07, 1.3732e-12, 5.3152e-11, 1.0017e-08,
         3.5293e-04, 3.0331e-05, 1.7735e-11, 1.6111e-06, 4.4681e-08, 3.7177e-12,
         1.1229e-05, 1.3669e-07, 4.6986e-06, 5.6337e-05, 9.6423e-10, 9.3342e-10,
         6.0830e-15, 7.1186e-26],
        [7.4018e-01, 1.1062e-03, 6.6063e-08, 1.3741e-09, 1.0844e-07, 5.9436e-05,
         1.1757e-03, 2.6706e-07, 9.2180e-11, 1.2576e-06, 1.2619e-07, 3.5501e-10,
         2.0316e-04, 7.0657e-06, 2.5725e-01, 1.5151e-05, 3.0153e-10, 6.7233e-09,
         1.9610e-17, 6.0341e-36],
        [3.2150e-05, 1.1261e-08, 2.8658e-08, 2.3015e-11, 3.3278e-24, 8.2558e-11,
         8.6748e-02, 6.7061e-08, 4.1312e-11, 6.1413e-06, 3.7265e-09, 3.0632e-11,
       

In [25]:
model_types = ['ak8_points_pf_sv_full', 'ak4_points_pf_sv_CHS_eta4p7', 'ak8_points_pf_sv_mass_decorr', 'ak8_points_pf_sv_mass_regression']
models = export_multiple_models(model_types)

Export model type - ak8_points_pf_sv_full


/Users/nirmalthomas/Library/Python/3.8/lib/python/site-packages/torch/onnx/symbolic_helper.py:719: UserWarning: allowzero=0 by default. In order to honor zero value in shape use allowzero=1
  warnings.warn("allowzero=0 by default. In order to honor zero value in shape use allowzero=1")
2022-11-07 18:16:10.644374 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:10.663616 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:10.663630 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:10.663637 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not u

Model output - 
tensor([[5.2472e-01, 1.1307e-01, 6.2028e-07, 8.6310e-08, 2.1301e-08, 5.4420e-05,
         1.5969e-02, 5.5414e-10, 7.2570e-10, 2.4125e-04, 6.0248e-11, 1.4272e-09,
         1.8701e-01, 4.4403e-09, 1.5819e-01, 7.4600e-04, 2.9107e-12, 1.6321e-06,
         3.5639e-18, 1.4696e-19],
        [1.2894e-01, 1.4772e-04, 2.6657e-07, 4.7445e-09, 1.4293e-12, 1.2452e-09,
         5.8327e-03, 3.1170e-05, 1.1815e-08, 7.6118e-03, 1.9609e-05, 4.8386e-08,
         1.0332e-01, 7.7149e-05, 7.5380e-01, 2.1889e-04, 6.5369e-07, 1.3122e-06,
         6.1282e-12, 7.7276e-21],
        [9.9038e-01, 9.4815e-06, 1.2748e-08, 2.0037e-13, 1.7461e-17, 2.2494e-09,
         3.0224e-03, 1.5983e-07, 2.8164e-13, 3.0545e-05, 1.5454e-09, 6.3218e-13,
         4.2614e-03, 1.9913e-07, 1.7270e-03, 5.7347e-04, 6.4928e-11, 1.2486e-10,
         1.7405e-20, 1.1171e-34],
        [2.6612e-03, 2.5503e-03, 1.0073e-03, 1.2958e-03, 2.6586e-07, 6.7891e-06,
         4.3576e-02, 1.1340e-04, 6.6539e-05, 3.1434e-01, 2.9731e-05, 1.4

2022-11-07 18:16:13.158064 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:13.174811 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:13.174826 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:13.174832 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:13.174838 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:13.174843 [W:onnxruntime:, gr

Model output - 
tensor([[1.8845e-01, 2.7349e-01, 9.4459e-02, 8.1806e-02, 6.8261e-03, 1.5388e-01,
         2.0109e-01, 1.4155e-06],
        [2.6895e-03, 1.1453e-05, 1.0236e-02, 3.5841e-04, 3.3342e-03, 7.9586e-02,
         4.6605e-02, 8.5718e-01],
        [3.3728e-01, 1.9112e-01, 1.6546e-01, 1.1601e-01, 1.2509e-02, 7.2156e-02,
         1.0539e-01, 7.6428e-05],
        [2.2686e-01, 4.3943e-01, 4.9339e-02, 3.6539e-02, 2.1000e-03, 6.3349e-02,
         1.8146e-01, 9.2299e-04],
        [1.6122e-01, 6.1216e-01, 4.8465e-02, 6.3720e-02, 2.9442e-04, 1.8954e-02,
         9.5180e-02, 1.0963e-05],
        [2.0513e-02, 9.7293e-01, 2.6028e-04, 2.3966e-03, 9.9060e-07, 8.4154e-05,
         3.8181e-03, 2.6906e-15],
        [1.8874e-01, 2.9103e-02, 6.7075e-02, 1.1245e-02, 2.4689e-02, 2.7710e-01,
         3.8886e-01, 1.3191e-02],
        [1.1531e-02, 9.8459e-01, 1.3611e-04, 1.9865e-03, 6.0612e-07, 3.7641e-05,
         1.7222e-03, 1.8771e-17],
        [3.9614e-02, 8.3492e-01, 7.0894e-03, 1.9568e-02, 1.9537e

2022-11-07 18:16:16.010414 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:16.028009 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:16.028024 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:16.028031 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:16.028037 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:16.028042 [W:onnxruntime:, gr

Model output - 
tensor([[1.5348e-11, 6.2136e-11, 5.3534e-27, 1.0000e+00, 1.8184e-07, 1.0113e-08,
         2.0744e-13, 1.9256e-40],
        [5.6951e-13, 2.3663e-09, 2.0404e-23, 1.0000e+00, 1.8224e-06, 1.5809e-07,
         4.0333e-14, 2.5726e-21],
        [2.4476e-08, 3.4888e-12, 4.5546e-25, 1.0000e+00, 2.1767e-22, 6.0520e-15,
         2.3351e-33, 4.3591e-36],
        [1.7418e-06, 7.8784e-07, 1.4541e-17, 1.0000e+00, 1.1049e-09, 1.6540e-10,
         1.1422e-14, 1.2090e-22],
        [4.3878e-13, 1.1314e-13, 1.5745e-31, 1.0000e+00, 8.4855e-15, 1.1397e-11,
         2.1173e-23, 3.2226e-36],
        [7.2572e-10, 8.5088e-11, 8.4095e-22, 1.0000e+00, 4.4529e-14, 1.9013e-10,
         3.6090e-22, 2.5641e-30],
        [8.3776e-22, 8.2122e-14, 1.8628e-33, 1.0000e+00, 6.1780e-16, 3.6019e-15,
         3.0829e-28, 0.0000e+00],
        [8.4134e-06, 1.0737e-07, 3.9016e-20, 9.9999e-01, 5.2902e-15, 3.6825e-06,
         1.6775e-20, 4.2842e-32],
        [2.0500e-08, 4.2122e-11, 5.6488e-24, 1.0000e+00, 3.4072e

2022-11-07 18:16:18.875966 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:18.891595 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:18.891608 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:18.891614 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:18.891619 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:18.891625 [W:onnxruntime:, gr

In [26]:
test_exported_models(models, model_types)

Model Type - ak8_points_pf_sv_full

------------
Config - Num Jets = 1 | Num particles per jet = 13
PT inference - 
tensor([[9.9717e-01, 1.5936e-03, 1.1684e-09, 8.0910e-12, 3.2486e-11, 3.3310e-10,
         2.1399e-04, 3.4275e-06, 9.1227e-10, 2.6549e-05, 2.1156e-09, 4.0993e-10,
         2.8850e-04, 1.2905e-08, 6.3273e-05, 6.4009e-04, 2.8466e-11, 4.3183e-10,
         6.4453e-18, 4.9030e-26]], grad_fn=<SoftmaxBackward0>)



2022-11-07 18:16:23.636800 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:23.652372 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:23.652384 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:23.652390 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:23.652396 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:23.652401 [W:onnxruntime:, gr

ORT inference - 
[array([[9.97170627e-01, 1.59361004e-03, 1.16836074e-09, 8.09101484e-12,
        3.24854310e-11, 3.33097744e-10, 2.13986146e-04, 3.42756266e-06,
        9.12273201e-10, 2.65493381e-05, 2.11565210e-09, 4.09929063e-10,
        2.88504263e-04, 1.29053035e-08, 6.32732481e-05, 6.40089274e-04,
        2.84663595e-11, 4.31832431e-10, 6.44536155e-18, 4.90299732e-26]],
      dtype=float32)]

Config - Num Jets = 1 | Num particles per jet = 1
PT inference - 
tensor([[9.9104e-01, 8.4595e-06, 6.0825e-06, 3.7309e-10, 1.8490e-10, 8.6133e-08,
         5.0306e-03, 4.8611e-05, 2.5785e-10, 1.6973e-04, 3.9118e-07, 4.4247e-10,
         2.3097e-03, 2.6691e-06, 3.9012e-04, 9.9179e-04, 5.3788e-08, 3.4778e-08,
         5.3975e-13, 2.6436e-21]], grad_fn=<SoftmaxBackward0>)



2022-11-07 18:16:24.540492 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:24.556350 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:24.556364 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:24.556371 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:24.556376 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:24.556381 [W:onnxruntime:, gr

ORT inference - 
[array([[9.9104160e-01, 8.4595085e-06, 6.0825419e-06, 3.7308778e-10,
        1.8490404e-10, 8.6134257e-08, 5.0305850e-03, 4.8610960e-05,
        2.5784935e-10, 1.6973270e-04, 3.9118717e-07, 4.4246914e-10,
        2.3097307e-03, 2.6691089e-06, 3.9012151e-04, 9.9179544e-04,
        5.3788774e-08, 3.4777830e-08, 5.3975270e-13, 2.6436014e-21]],
      dtype=float32)]

Config - Num Jets = 17 | Num particles per jet = 3
PT inference - 
tensor([[1.4427e-01, 5.2076e-02, 8.4423e-06, 9.4510e-07, 1.2903e-07, 1.5530e-04,
         2.8820e-02, 2.1219e-08, 1.3760e-08, 4.8182e-04, 7.0497e-09, 1.5444e-08,
         3.0165e-01, 1.5294e-06, 4.6212e-01, 1.0418e-02, 3.1009e-09, 1.1700e-06,
         5.2680e-16, 1.5087e-19],
        [8.6123e-01, 3.9115e-06, 8.4377e-05, 1.1744e-09, 1.4007e-11, 2.2377e-11,
         4.2257e-04, 5.6799e-05, 4.7638e-10, 6.3611e-02, 6.2121e-07, 2.2457e-10,
         5.0662e-02, 2.5061e-07, 2.3557e-02, 3.7059e-04, 9.1526e-13, 8.6515e-07,
         2.9421e-16, 6.5824e-2

2022-11-07 18:16:25.762372 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:25.778140 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:25.778154 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:25.778160 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:25.778166 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:25.778171 [W:onnxruntime:, gr

ORT inference - 
[array([[1.4426576e-01, 5.2075531e-02, 8.4422918e-06, 9.4509465e-07,
        1.2902713e-07, 1.5530098e-04, 2.8820300e-02, 2.1219313e-08,
        1.3759900e-08, 4.8181793e-04, 7.0496449e-09, 1.5443696e-08,
        3.0164728e-01, 1.5293774e-06, 4.6212348e-01, 1.0418265e-02,
        3.1008929e-09, 1.1700295e-06, 5.2679811e-16, 1.5086721e-19],
       [8.6122972e-01, 3.9114707e-06, 8.4377811e-05, 1.1744424e-09,
        1.4006870e-11, 2.2377622e-11, 4.2257766e-04, 5.6799461e-05,
        4.7638032e-10, 6.3611045e-02, 6.2121728e-07, 2.2456735e-10,
        5.0661948e-02, 2.5061607e-07, 2.3557320e-02, 3.7058763e-04,
        9.1526960e-13, 8.6515541e-07, 2.9421488e-16, 6.5826175e-27],
       [2.0437935e-02, 2.9968680e-03, 1.6321160e-04, 6.5457927e-05,
        9.7238160e-07, 4.6181253e-06, 7.3320554e-03, 1.6710961e-04,
        8.3752704e-05, 1.5983771e-01, 9.0480689e-06, 8.1895472e-05,
        5.0497764e-01, 2.1346645e-05, 2.9481888e-01, 8.5207978e-03,
        1.5273561e-07, 4.805

2022-11-07 18:16:28.431118 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:28.447585 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:28.447600 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:28.447607 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:28.447613 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:28.447619 [W:onnxruntime:, gr

ORT inference - 
[array([[8.04614723e-01, 1.39988780e-01, 7.43380806e-05, 2.52350619e-05,
        1.50718995e-06, 1.63117703e-02, 3.00600901e-02, 6.42144179e-04,
        9.46520595e-06, 3.19270403e-05, 1.23578593e-06, 3.54242331e-07,
        2.38899476e-04, 7.26094959e-06, 6.50051050e-04, 7.33928476e-03,
        4.41167060e-07, 2.40214695e-06, 1.63075831e-10, 9.56412616e-14],
       [7.76238203e-01, 1.12915978e-01, 8.18196975e-04, 2.27215831e-04,
        1.35004882e-07, 4.22874205e-02, 5.54570444e-02, 2.26570133e-04,
        1.26730320e-05, 8.24797389e-05, 2.51761026e-06, 2.05245965e-06,
        6.88948261e-04, 3.69344962e-05, 3.41958064e-03, 7.57115660e-03,
        8.77289585e-06, 4.06851177e-06, 1.00651110e-09, 1.05541017e-13],
       [8.84328544e-01, 5.03668264e-02, 4.83945496e-06, 4.95803647e-07,
        1.65987810e-08, 3.44060281e-05, 9.72389430e-03, 1.14588918e-04,
        1.73406011e-06, 3.55568761e-03, 9.44630301e-06, 3.94993867e-06,
        1.49687408e-02, 4.19637363e-05, 1.70

2022-11-07 18:16:29.551637 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:29.568256 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:29.568272 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:29.568279 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:29.568284 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:29.568290 [W:onnxruntime:, gr

ORT inference - 
[array([[1.5930660e-01, 7.6107818e-01, 8.0789551e-03, 2.1060502e-02,
        5.0921849e-04, 2.6319303e-02, 2.3647308e-02, 5.0120363e-14]],
      dtype=float32)]

Config - Num Jets = 1 | Num particles per jet = 1
PT inference - 
tensor([[3.0624e-02, 9.4193e-01, 3.4548e-04, 8.2619e-04, 3.8231e-06, 6.2555e-04,
         2.5650e-02, 8.1772e-12]], grad_fn=<SoftmaxBackward0>)



2022-11-07 18:16:30.432210 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:30.449280 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:30.449296 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:30.449302 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:30.449308 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:30.449313 [W:onnxruntime:, gr

ORT inference - 
[array([[3.0623935e-02, 9.4192535e-01, 3.4548162e-04, 8.2619471e-04,
        3.8231010e-06, 6.2555179e-04, 2.5649702e-02, 8.1771308e-12]],
      dtype=float32)]

Config - Num Jets = 17 | Num particles per jet = 3
PT inference - 
tensor([[2.7259e-01, 3.5354e-02, 7.4021e-02, 1.1774e-02, 3.2873e-02, 2.2242e-01,
         3.0376e-01, 4.7206e-02],
        [1.9596e-01, 3.2687e-01, 5.8642e-02, 4.3274e-02, 5.6750e-03, 1.2171e-01,
         2.4786e-01, 5.9336e-10],
        [4.9477e-03, 9.9435e-01, 4.6335e-05, 3.0045e-04, 5.8505e-08, 1.8953e-05,
         3.3390e-04, 2.1076e-25],
        [4.4555e-01, 2.8581e-02, 1.7608e-01, 3.4464e-02, 9.3592e-03, 4.1656e-02,
         5.4173e-02, 2.1014e-01],
        [1.2944e-01, 7.4547e-01, 1.3285e-02, 1.4923e-02, 6.5476e-04, 1.6473e-02,
         7.9746e-02, 6.7227e-14],
        [3.2043e-02, 3.8255e-03, 3.8065e-02, 1.6600e-02, 1.3448e-03, 1.8567e-02,
         1.1501e-02, 8.7805e-01],
        [4.8040e-02, 1.3462e-02, 8.2527e-03, 2.0438e-02, 2.7350e

2022-11-07 18:16:31.124828 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:31.141470 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:31.141485 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:31.141491 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:31.141496 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:31.141502 [W:onnxruntime:, gr

ORT inference - 
[array([[2.72592753e-01, 3.53535712e-02, 7.40208104e-02, 1.17736682e-02,
        3.28730233e-02, 2.22424492e-01, 3.03755671e-01, 4.72059436e-02],
       [1.95959583e-01, 3.26874256e-01, 5.86420596e-02, 4.32743244e-02,
        5.67505462e-03, 1.21712975e-01, 2.47861713e-01, 5.93353922e-10],
       [4.94768238e-03, 9.94352579e-01, 4.63348297e-05, 3.00450309e-04,
        5.85041775e-08, 1.89530583e-05, 3.33893724e-04, 2.10766106e-25],
       [4.45548922e-01, 2.85807550e-02, 1.76076263e-01, 3.44640240e-02,
        9.35924705e-03, 4.16564792e-02, 5.41725382e-02, 2.10141763e-01],
       [1.29443720e-01, 7.45474756e-01, 1.32848928e-02, 1.49230929e-02,
        6.54762960e-04, 1.64731853e-02, 7.97456056e-02, 6.72284833e-14],
       [3.20429876e-02, 3.82547826e-03, 3.80649194e-02, 1.66002288e-02,
        1.34478323e-03, 1.85668413e-02, 1.15007041e-02, 8.78054082e-01],
       [4.80400436e-02, 1.34616429e-02, 8.25266819e-03, 2.04377249e-02,
        2.73502610e-05, 3.64459294e-04, 

2022-11-07 18:16:32.503411 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:32.519942 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:32.519958 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:32.519964 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:32.519969 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:32.519975 [W:onnxruntime:, gr

ORT inference - 
[array([[2.74361461e-01, 2.26845980e-01, 7.74123520e-02, 6.88421279e-02,
        1.52503075e-02, 2.35200822e-01, 1.02086872e-01, 1.14357213e-07],
       [2.62106627e-01, 4.26176220e-01, 3.69423814e-02, 4.98180836e-02,
        3.04927514e-03, 1.05268963e-01, 1.16638385e-01, 1.06235689e-07],
       [1.80278361e-01, 5.77950299e-01, 2.96700541e-02, 4.52489704e-02,
        2.65997974e-03, 1.09689564e-01, 5.45027591e-02, 3.60317185e-15],
       [1.41447842e-01, 5.11162460e-01, 2.84952596e-02, 3.76894437e-02,
        2.12214701e-03, 1.24708176e-01, 1.54374704e-01, 2.47543305e-13],
       [2.21616179e-01, 5.19513965e-01, 2.78846510e-02, 6.65798634e-02,
        3.54136853e-03, 1.31049097e-01, 2.98149586e-02, 5.67667224e-13],
       [1.95040032e-01, 7.35421062e-01, 9.30084474e-03, 2.09491905e-02,
        5.93090546e-04, 2.90786009e-02, 9.61716194e-03, 3.04141918e-14],
       [2.58439898e-01, 5.68701625e-01, 1.87717043e-02, 2.89268475e-02,
        1.48984673e-03, 3.95862535e-02, 

2022-11-07 18:16:33.431957 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:33.448197 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:33.448212 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:33.448219 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:33.448224 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:33.448230 [W:onnxruntime:, gr

ORT inference - 
[array([[4.5542702e-11, 1.0860134e-07, 1.7307309e-18, 9.9998808e-01,
        1.1683920e-06, 1.0583399e-05, 2.7522237e-14, 1.0528567e-27]],
      dtype=float32)]

Config - Num Jets = 1 | Num particles per jet = 1
PT inference - 
tensor([[7.8788e-19, 3.9223e-15, 3.2286e-33, 1.0000e+00, 1.2271e-23, 1.0789e-24,
         7.6821e-37, 2.9217e-42]], grad_fn=<SoftmaxBackward0>)



2022-11-07 18:16:34.361038 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:34.377575 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:34.377591 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:34.377598 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:34.377603 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:34.377609 [W:onnxruntime:, gr

ORT inference - 
[array([[7.8788364e-19, 3.9222627e-15, 3.2285889e-33, 1.0000000e+00,
        1.2271805e-23, 1.0789208e-24, 7.6832285e-37, 0.0000000e+00]],
      dtype=float32)]

Config - Num Jets = 17 | Num particles per jet = 3
PT inference - 
tensor([[4.9618e-16, 1.7496e-14, 7.2168e-26, 1.0000e+00, 5.3492e-11, 8.9727e-13,
         2.9314e-17, 3.2226e-26],
        [3.8468e-12, 6.7787e-07, 8.8257e-21, 1.0000e+00, 1.8599e-07, 5.2133e-08,
         2.0700e-14, 5.6300e-26],
        [8.0340e-25, 4.5879e-14, 1.2426e-35, 1.0000e+00, 3.2475e-12, 4.9934e-14,
         2.0299e-26, 1.4013e-45],
        [1.6058e-16, 4.8714e-13, 4.0974e-27, 1.0000e+00, 7.6948e-10, 2.6448e-10,
         2.3415e-16, 1.8863e-27],
        [1.4493e-11, 1.6312e-12, 6.0847e-24, 1.0000e+00, 2.3754e-20, 5.1635e-14,
         4.5453e-30, 1.1222e-32],
        [7.4468e-18, 2.0191e-10, 3.5407e-25, 1.0000e+00, 5.1898e-14, 6.7160e-12,
         5.8499e-26, 7.4831e-38],
        [2.2193e-08, 5.1372e-09, 1.9385e-27, 9.9999e-01, 1.8277e

2022-11-07 18:16:35.576074 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:35.592372 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:35.592389 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:35.592396 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:35.592402 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:35.592422 [W:onnxruntime:, gr

ORT inference - 
[array([[4.9617025e-16, 1.7495676e-14, 7.2167473e-26, 1.0000000e+00,
        5.3491680e-11, 8.9726111e-13, 2.9313785e-17, 3.2226817e-26],
       [3.8467979e-12, 6.7786738e-07, 8.8256456e-21, 9.9999905e-01,
        1.8599339e-07, 5.2132918e-08, 2.0699398e-14, 5.6299302e-26],
       [8.0339631e-25, 4.5878316e-14, 1.2426146e-35, 1.0000000e+00,
        3.2475097e-12, 4.9932934e-14, 2.0299705e-26, 0.0000000e+00],
       [1.6057980e-16, 4.8714342e-13, 4.0973986e-27, 1.0000000e+00,
        7.6949203e-10, 2.6448313e-10, 2.3415527e-16, 1.8862878e-27],
       [1.4492777e-11, 1.6311232e-12, 6.0845627e-24, 1.0000000e+00,
        2.3753664e-20, 5.1635532e-14, 4.5454286e-30, 1.1221353e-32],
       [7.4468845e-18, 2.0190437e-10, 3.5406947e-25, 1.0000000e+00,
        5.1897184e-14, 6.7158991e-12, 5.8498541e-26, 7.4830874e-38],
       [2.2193010e-08, 5.1372049e-09, 1.9385053e-27, 9.9998951e-01,
        1.8277284e-06, 8.7053140e-06, 1.8013716e-10, 2.5350654e-21],
       [7.1544225e-13, 

2022-11-07 18:16:37.600241 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:37.616471 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:37.616484 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:37.616490 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:37.616495 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:37.616500 [W:onnxruntime:, gr

ORT inference - 
[array([[4.0541153e-08, 7.9264595e-10, 7.7395176e-22, 9.9867541e-01,
        1.2778619e-03, 4.6648682e-05, 2.9348985e-09, 1.3649316e-18],
       [9.9710373e-09, 1.3918958e-07, 9.2988946e-15, 9.9329621e-01,
        2.4661890e-03, 4.2371782e-03, 3.1055751e-07, 1.0242005e-17],
       [7.8218499e-12, 2.3233412e-08, 1.5838935e-17, 9.9996424e-01,
        7.2888236e-07, 3.5054371e-05, 1.3314559e-14, 1.8886232e-29],
       [1.2584311e-08, 4.3001251e-09, 6.4389145e-19, 9.9815923e-01,
        7.1605126e-04, 1.1246963e-03, 4.6664621e-08, 5.0468331e-19],
       [2.4471344e-06, 2.3342816e-06, 1.1190267e-14, 9.8697585e-01,
        2.1580253e-03, 1.0860048e-02, 1.2794676e-06, 7.0392648e-18],
       [7.8724416e-10, 9.8761377e-10, 1.1231087e-18, 9.9907136e-01,
        4.1623402e-06, 9.2440011e-04, 5.1766486e-10, 3.3973147e-24],
       [4.7923922e-11, 1.6046091e-09, 4.4731873e-20, 9.9987376e-01,
        1.7239990e-06, 1.2450917e-04, 5.0524521e-13, 9.2727945e-30],
       [3.9824012e-11, 

2022-11-07 18:16:38.733881 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:38.750581 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:38.750595 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:38.750602 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:38.750608 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:38.750614 [W:onnxruntime:, gr

ORT inference - 
[array([[1.]], dtype=float32)]

Config - Num Jets = 1 | Num particles per jet = 1
PT inference - 
tensor([[1.]], grad_fn=<SoftmaxBackward0>)



2022-11-07 18:16:39.715439 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:39.730090 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:39.730101 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:39.730107 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:39.730112 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:39.730118 [W:onnxruntime:, gr

ORT inference - 
[array([[1.]], dtype=float32)]

Config - Num Jets = 17 | Num particles per jet = 3
PT inference - 
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]], grad_fn=<SoftmaxBackward0>)



2022-11-07 18:16:40.896691 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:40.913129 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:40.913143 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:40.913149 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:40.913154 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:40.913160 [W:onnxruntime:, gr

ORT inference - 
[array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)]

Config - Num Jets = 16 | Num particles per jet = 20
PT inference - 
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]], grad_fn=<SoftmaxBackward0>)



2022-11-07 18:16:42.917292 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_459'
2022-11-07 18:16:42.936609 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '184'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:42.936624 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '185'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:42.936629 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '174'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:42.936634 [W:onnxruntime:, graph.cc:3559 CleanUnusedInitializersAndNodeArgs] Removing initializer '181'. It is not used by any node and should be removed from the model.
2022-11-07 18:16:42.936639 [W:onnxruntime:, gr

ORT inference - 
[array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)]

